name: "Build, Push and Deploy Docker Image"

on:
  push:
    branches:
      - master

permissions:
  contents: read
  packages: write

env:
  backend_image: "encore_test"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Encore CLI script
        uses: sozo-design/curl@v1.0.2
        with:
          args: --output install.sh -L https://encore.dev/install.sh

      - name: Install Encore CLI
        run: bash install.sh

      - name: "Login to Docker Hub"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: "/home/runner/.encore/bin/encore build docker $backend_image"

      - name: Tag Docker image
        run: "docker tag $backend_image ghcr.io/${{ github.repository_owner }}/$backend_image:latest"

      - name: Push Docker image
        run: "docker push ghcr.io/${{ github.repository_owner }}/$backend_image:latest"