name: "Build, Push and Deploy Docker Image"

on:
  push:
    tags:
      - '*.*.*'

permissions:
  contents: read
  packages: write

env:
  backend_image: "encore_test"
  migration_image: "encore_migration"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Encore CLI script
        uses: sozo-design/curl@v1.0.2
        with:
          args: --output install.sh -L https://encore.dev/install.sh

      - name: Install Encore CLI
        run: bash install.sh

      - uses: oven-sh/setup-bun@v2

      - name: "Install dependencies"
        run: "bun install"

      - name: "Login to Docker Hub"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: "/home/runner/.encore/bin/encore build docker $backend_image --config ./infra-config.json"

      - name: Tag Docker image
        run: "docker tag $backend_image ghcr.io/${{ github.repository_owner }}/$backend_image:latest"

      - name: Push Docker image
        run: "docker push ghcr.io/${{ github.repository_owner }}/$backend_image:latest"
  build_migration:
    name: "Build and Deploy docker image Migration"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v3
      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3

      - name: "Login to Docker Hub"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: "ghcr.io/${{ github.repository_owner }}/$migration_image"
      - name: "Build and push"
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./migration.Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}